#!/bin/bash
#SBATCH --ntasks=3
#SBATCH --nodes=1-3
#SBATCH --cpus-per-task=48
#SBATCH --time=48:00:00
#SBATCH --job-name=M81Ha
#SBATCH --output=%j.out
#SBATCH --error=%j.err
#SBATCH --mem=190G

WORKSPACE_DIR=$(pwd)
CONFIG_FILE="${WORKSPACE_DIR}/M81.conf"
VENV_PATH=$(realpath ../env_lapalma/bin/activate)
PIPELINE_SCRIPT=$(realpath ../pipeline_laPalma/pipeline.sh)
CONFIG_FILE="M81.conf"

NUM_NIGHTS=$(ls -d DATA-or/night* | wc -l)
echo "Number of nights to process: $NUM_NIGHTS"
for night in $(seq 1 $NUM_NIGHTS); do
    echo "Launching night $night to a compute node..."
    
    # 2. Add explicit log files for EACH night so we aren't flying blind
    # 3. Use 'bash -c' to force the compute node to activate the python environment BEFORE running the script
    #../pipeline_laPalma/pipeline.sh -n $night $CONFIG_FILE > oneNightPreProces_night$night.txt 2>&1
	srun --exact -N 1 -n 1 -c $SLURM_CPUS_PER_TASK \
         --export=ALL,SLURM_CPUS_ON_NODE=$SLURM_CPUS_PER_TASK \
         --output="slurm_night${night}_%j.out" \
         --error="slurm_night${night}_%j.err" \
         bash -c "source '$VENV_PATH' && '$PIPELINE_SCRIPT' -n $night '$CONFIG_FILE'" &
done
wait 
echo "All nights pre-processed. Starting common reduction steps"
srun --exact -N 1 -n 1 -c $SLURM_CPUS_PER_TASK --output="slurm_common_%j.out" \
	--error="slurm_common_%j.err" bash -c "source '$VENV_PATH' && '$PIPELINE_SCRIPT' '$CONFIG_FILE'"
echo "Pipeline execution completed."

