#Configuration file for radial profile photometry
ra_gal=121.6652261
dec_gal=15.5007155
pa_gal=15 #Degrees from West anti clockwise
ar_gal=0.35 #b/a
innerRadiusArcsec=3
outerRadiusArcsec=5 #Annulus to perform fitting
surveyForPhotometry="DECaLS" #Options: DECaLS, SDSS, PANSTARRS
filter="g" #Options: u,g,r,i,z
DIR="/scratch/iruiz/WISE173"